language: node_js
install:
- npm update -g npm
- npm install -g typescript
- npm install
jobs:
  include:
  - stage: test
    script: npm test
    node_js:
    - '6'
    - '7'
    - '8'
  - stage: npm release
    node_js: '8'
    script: echo "Deploying to npm ..."
    deploy:
      provider: npm
      skip_cleanup: true
      email: engineering@foundry.ai
      api_key:
        secure: CCVMu68PkLFKxWhI5/YqwoP+J/IWeVqb19yB3v4jF90naHmiQF9of73BsyOV4VE7tXI5NJs7oAAZxMkZHqdPklpkjnQZy1PoqJWFNVOnv4gmSAWaDLnxI0vbWTUgaHRNzzXkARrhD+m+X6sAdJowldibM0406kQ3d0vBKphkv1VfC9T6jJcMA2tuVTkLIKU2Jl5dYpmyPLILB4SWAdkY7SyscEyFlJ6FQJGy4Sd3rAcVz/I7p4Wk1iEH4YIgxx1qvf6p+Q1BIag/IVwPVPzGLnCrEombqOHTMZoAl9XdwI03IsqshnEdUlRypoJ0byngTvIx9Ya01IVv2bCTw+QQHGCHhmVFV2P52AhfNZawxkWu/QzpFldk8+eZO0/OtdP/S3KqXq5Lk5SHj6B6nm0ztHEyTU6jdMjjtLx0k48wJvLKKwjVXc//Gg4tcea201gbqfp2pRgVS/yrX/ftUbWfTEBLq64adbb/b60TZA3GsP4WnZF+qlXJcUJ25AzU0WeatAYsjs3kOh9G8D87DJWjeltE/bXWPZsu5luCr+fC3BqD03rnhDCWznmUJizaswsJTFGCSFzyT0Xxo1U7GUkWpXNSxjriboEPSls1RMs1B3zmZbALNbZzImSdTjsRVwGP8f1A0cLP/YjSgLga8ZyO/Ikjq5YyNJF9qzEigzsbYPo=
      on:
        tags: true