language: node_js
install:
- npm update -g npm
- npm install -g typescript
- npm install
jobs:
  include:
  - stage: test
    script: npm test
    node_js:
    - '6'
    - '7'
    - '8'
  - stage: npm release
    node_js: '8'
    script: echo "Deploying to npm ..."
    deploy:
      provider: npm
      skip_cleanup: true
      email: engineering@foundry.ai
      api_key:
        secure: QAgsLrE5fdTwM4uBGB+bg2iab1xEIyXA5uXCgRlRYO0esiOfzoWpdeo2+gBa9aHURsyS5pgxnecxgV8hcXpfHSLaLEYDGvGnOpuD+rWanl3SQHT8MXnf0JhlO8wWNda6cscCvDwGOwC3ibmQaycY4nrMymJiDhjbwkoNg8aeq3NqWVgzb6sNhNt0lpNkYxcwjtXDuSrSEQy53p7WDj+lgs2ndn97orBCcSoBpUbPUib6XpuKeDc3dULG1q9SEuZt/u+qVRQZdCu1C49V9NLPVJTff4fyKg1cc8jdCzQxQQNYLU+Ji+KeY/tircna0ptHV89SLCZxRKIUNGMSo4gHfD1slwPiebH/YREmXmBwy6tJj0wjhJ1ep+jJnNVGnRAtKJRaLZr+7ixsYWH4s1XEoKTDie/gfPZr3qUdVh2b4lhMrHP3cd/XLNQ+o452BPfzcuxxorrU2uOHzwHhhR0Pwu2hDLWYV6rl87+NKtHMRhsjRIGyHbHSj9MyGSdscWi4t4mGRGIuL+HGRRpRsD5Tv+akxzNw8wNV8B4yjMGRXtUHs3PLvX6fJrThpKYjhi7aGtRVr3fqeZVxwvAd1otpkjjMB3JPWPYhpDXPav0C0zqUA+ybiVdVg4/TKcjI5lF52vg/GT0icja5aVFWC4iJnxFirJR5KGyCSzDaAmvi4UI=
      on:
        tags: true
deploy:
  api_key:
    secure: D8rNcL59he8Qi47Z9GavXTDNsgdtRnXO0Pi7MiM/bnqRbvrzKBTGzS1PKyMuCk1I3cqofPLHi07c5oUGTkF344XrxrtAMihTHFhHJwHtOspiVJn5K7wN9ydvfWzsP4cceaFyXKRi46tY93gGNUwW1/WaCFvXvEB5azDBY4ATFsUWsHhwnoGvMgFQuLYgqswFf0X3msvT2zoXOx8mLZjYXOPdlKKf0FLaUOf+yxnTKc6WeNifEXPAQlKio0sEqPWP0hfS9ZNPOn/CQsKlIoNEfl/6y2CM+o84Hvi4xOoNOeFOsyYvwj28wgEjeVB/q7Y+uYDr8gMed5HR5y0fxev4LL4ouffgtu2v11UracpZ3pmjW0+2aq4k6pREhU6s4CPm5Z0vv5vh4PeQCI6qxRQUmNKfkntDaliqoMSptFBpjp4yEdoBw2eFhreypLqC62hJueKRE+J4cV7tKk1GTTXNahIrnuqCi/+/RPwfvZ9jQRdShrK22/F4O6btW5BnRfTanB+O8mVwE8aW2+WoLl4Xt4obzNN8Ra5SXnbCk6Dr8PuvZYaTgxkFdcUn+Y99houcXtr9nNCfPjyiylYpvfdUP2ZIilMs03pdfAyLKmRtUf9O5zcs3ZCLfPM70JOL4Q1AkKiImWWDOUIst2wrbbc23eM5PHSfHYlzGb7oe08N6SM=
